#Recommend System

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

###data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# data
path = '/content/drive/Shareddrives/데캡디/Result/Recommendation_data'
df_priv = pd.read_csv(path + '/final_x_y_priv.csv')
df_corp = pd.read_csv(path + '/final_x_y_corp.csv')
df_priv_raw = pd.read_csv(path + '/raw_x_y_priv.csv')
df_corp_raw = pd.read_csv(path + '/raw_x_y_corp.csv')
df_card_priv = pd.read_csv(path + '/final_card_priv.csv')
df_LN = pd.read_csv('/content/drive/Shareddrives/데캡디/DataSet/SDB2/SDB2_P_LN.csv')

In [ ]:
df_priv

,JOIN_SN,CD_USG_AMT,CD_CA_AMT,AGE,CD_OPN_CD_2_1,GENDER,CD_CA_LMT,DLQ_CD_1_101,CD_USG_LMT,DLQ_RGST_AMT_max,...,SCTR_CD_21,DLQ_CD_1_105,PUB_DLQ_CD_1_604,is_applied,LN_CD_1,LN_CD_2,LN_CD_3,LN_DT,LN_AMT,RATE
0,787068,33040.0,0.0,38,5.0,2,5895.555556,0.0,23966.666667,0.0,...,0.0,0.0,0.0,1.0,31.0,100.0,0.0,201801.0,14000.0,4700.0
1,1630591,0.0,0.0,12,0.0,2,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,746631,21280.0,0.0,37,2.0,1,4400.000000,0.0,18750.000000,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,936890,0.0,0.0,12,0.0,1,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1850766,96010.0,0.0,63,3.0,1,4377.777778,0.0,30000.000000,0.0,...,0.0,0.0,0.0,1.0,31.0,100.0,0.0,201405.0,26000.0,4800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88387,1731608,70780.0,0.0,46,3.0,2,4540.000000,0.0,13640.000000,0.0,...,0.0,0.0,0.0,1.0,31.0,270.0,0.0,201807.0,35000.0,1300.0
88388,656440,16360.0,1100.0,49,4.0,1,15769.230769,0.0,30000.000000,0.0,...,0.0,0.0,0.0,1.0,31.0,220.0,0.0,201910.0,110000.0,2500.0
88389,656440,16360.0,1100.0,49,4.0,1,15769.230769,0.0,30000.000000,0.0,...,0.0,0.0,0.0,1.0,41.0,0.0,0.0,201807.0,1100.0,0.0
88390,285890,25370.0,0.0,60,4.0,2,4000.000000,0.0,12666.666667,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
88391,945641,0.0,0.0,28,0.0,2,0.000000,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_priv[df_priv['JOIN_SN'] == 496097]

,JOIN_SN,CD_USG_AMT,CD_CA_AMT,AGE,CD_OPN_CD_2_1,GENDER,CD_CA_LMT,DLQ_CD_1_101,CD_USG_LMT,DLQ_RGST_AMT_max,...,SCTR_CD_21,DLQ_CD_1_105,PUB_DLQ_CD_1_604,is_applied,LN_CD_1,LN_CD_2,LN_CD_3,LN_DT,LN_AMT,RATE
9,496097,30930.0,0.0,65,2.0,1,5892.0,0.0,18000.0,0.0,...,0.0,0.0,0.0,1.0,31.0,100.0,0.0,200003.0,40000.0,4080.0
10,496097,30930.0,0.0,65,2.0,1,5892.0,0.0,18000.0,0.0,...,0.0,0.0,0.0,1.0,31.0,100.0,0.0,201303.0,40000.0,4100.0

In [ ]:
df_priv_raw

,JOIN_SN,AGE,GENDER,DLQ_RGST_AMT_mean,DLQ_RGST_AMT_min,DLQ_RGST_AMT_max,DLQ_RGST_DT_count,DLQ_CD_1_101,DLQ_CD_1_201,DLQ_CD_1_202,...,CD_OPN_CD_1_81,CD_OPN_CD_1_83,CD_OPN_CD_2_1,CD_OPN_CD_2_2,CD_USG_LMT,CD_CA_LMT,CD_USG_AMT,CD_CA_AMT,GRNT_AMT,is_applied
0,787068,38,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,0.0,5.0,1.0,23966.666667,5895.555556,33040.0,0.0,0.0,1.0
1,1630591,12,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,746631,37,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,2.0,0.0,18750.000000,4400.000000,21280.0,0.0,0.0,0.0
3,936890,12,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
4,1850766,63,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,3.0,0.0,30000.000000,4377.777778,96010.0,0.0,2130000.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48280,158999,58,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
48281,1731608,46,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.0,0.0,3.0,0.0,13640.000000,4540.000000,70780.0,0.0,0.0,1.0
48282,656440,49,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,30000.000000,15769.230769,16360.0,1100.0,0.0,1.0
48283,285890,60,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.0,0.0,4.0,0.0,12666.666667,4000.000000,25370.0,0.0,0.0,0.0
48284,945641,28,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0

In [ ]:
df_priv_raw = df_priv_raw[df_priv_raw['is_applied'] == 1]

In [ ]:
df_priv_raw.reset_index(inplace = True, drop = True)
df_priv_raw_index = df_priv_raw.JOIN_SN.to_list()
df_priv_raw_index = pd.DataFrame(df_priv_raw_index)
df_priv_raw_index

             0
0       787068
1      1850766
2       680870
3       496097
4       407358
...        ...
16534  1868069
16535   686000
16536   545801
16537  1731608
16538   656440

[16539 rows x 1 columns]

In [ ]:
df_priv_raw.drop('is_applied', axis = 1 ,inplace = True)
# df_priv_raw.drop('JOIN_SN', axis = 1 ,inplace = True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [ ]:
df_priv_raw[df_priv_raw['AGE'] < 20]

,JOIN_SN,AGE,GENDER,DLQ_RGST_AMT_mean,DLQ_RGST_AMT_min,DLQ_RGST_AMT_max,DLQ_RGST_DT_count,DLQ_CD_1_101,DLQ_CD_1_201,DLQ_CD_1_202,...,SCTR_CD_21,CD_OPN_CD_1_81,CD_OPN_CD_1_83,CD_OPN_CD_2_1,CD_OPN_CD_2_2,CD_USG_LMT,CD_CA_LMT,CD_USG_AMT,CD_CA_AMT,GRNT_AMT
752,95793,19,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,2.0,0.0,3341.666667,741.666667,6330.0,4950.0,0.0
991,1879157,19,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1072,961104,18,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1105,1954547,18,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
1122,1564170,17,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16040,58690,19,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.000000,0.000000,0.0,0.0,0.0
16139,1564994,15,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
16259,420979,12,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
16287,1293900,18,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0
16481,867838,19,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0

In [ ]:
from sklearn.model_selection import train_test_split
df_train, df_test = train_test_split(df_priv_raw, test_size = 0.25, random_state = 42)

In [ ]:
df_test_index = df_test.JOIN_SN.to_list()

### User_Based Collaborative Filtering

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

####priv

In [ ]:
df_priv_raw_cs = pd.DataFrame(cosine_similarity(df_priv_raw))
df_priv_raw_cs['JOIN_SN'] = df_priv_raw_index[0]

In [ ]:
df_priv_raw_cs

,0,1,2,3,4,5,6,7,8,9,...,16530,16531,16532,16533,16534,16535,16536,16537,16538,JOIN_SN
0,1.000000,0.656340,0.998630,0.999768,0.998030,0.999134,0.999720,0.999406,0.999895,0.999371,...,0.994126,0.998630,0.998867,0.999424,0.998630,0.997485,0.999837,0.999733,0.999601,787068
1,0.656340,1.000000,0.655477,0.656250,0.655067,0.655796,0.656309,0.655896,0.656178,0.655878,...,0.653073,0.655477,0.655551,0.655804,0.655477,0.654981,0.656306,0.656384,0.655770,1850766
2,0.998630,0.655477,1.000000,0.997338,0.993864,0.999942,0.999425,0.999807,0.999136,0.999828,...,0.987924,1.000000,0.999965,0.999644,0.999999,0.992756,0.997777,0.999131,0.998359,680870
3,0.999768,0.656250,0.997338,1.000000,0.998939,0.998060,0.999151,0.998449,0.999374,0.998396,...,0.996163,0.997338,0.997639,0.998480,0.997338,0.998772,0.999937,0.999327,0.999184,496097
4,0.998030,0.655067,0.993864,0.998939,1.000000,0.994945,0.996715,0.995603,0.997265,0.995514,...,0.997505,0.993864,0.994350,0.995762,0.993864,0.999165,0.998915,0.997084,0.997500,407358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16534,0.998630,0.655477,0.999999,0.997338,0.993864,0.999941,0.999425,0.999806,0.999136,0.999827,...,0.987923,0.999999,0.999964,0.999644,1.000000,0.992755,0.997777,0.999131,0.998359,1868069
16535,0.997485,0.654981,0.992756,0.998772,0.999165,0.993943,0.996226,0.994540,0.996395,0.994449,...,0.999237,0.992755,0.993143,0.994531,0.992755,1.000000,0.998420,0.996801,0.996274,686000
16536,0.999837,0.656306,0.997777,0.999937,0.998915,0.998424,0.999372,0.998757,0.999524,0.998711,...,0.995638,0.997777,0.998040,0.998759,0.997777,0.998420,1.000000,0.999513,0.999295,545801
16537,0.999733,0.656384,0.999131,0.999327,0.997084,0.999472,0.999964,0.999522,0.999651,0.999509,...,0.993505,0.999131,0.999177,0.999336,0.999131,0.996801,0.999513,1.000000,0.998930,1731608
16538,0.999601,0.655770,0.998359,0.999184,0.997500,0.998857,0.999071,0.999271,0.999758,0.999232,...,0.992161,0.998359,0.998761,0.999501,0.998359,0.996274,0.999295,0.998930,1.000000,656440

In [ ]:
df_selected = df_priv_raw_cs.query('JOIN_SN in @df_test_index')

In [ ]:
# 0번째 test
df_serial = list(zip(df_priv_raw_cs[0], df_priv_raw_cs['JOIN_SN']))
sim_scores = sorted(df_serial, key = lambda x: x[0], reverse = True)
sim_scores = sim_scores[1:21]
sim_scores

[(0.99999799416539, 691574),
 (0.9999978395386411, 997869),
 (0.9999971104811358, 706288),
 (0.9999965930393888, 891848),
 (0.9999965562258663, 510055),
 (0.9999963836317004, 1015400),
 (0.9999963456837079, 460991),
 (0.9999959464638029, 886777),
 (0.9999958240858234, 964118),
 (0.9999954034183448, 850732),
 (0.9999944668816618, 876192),
 (0.9999942734652681, 595474),
 (0.9999936021273677, 727952),
 (0.999993481148329, 421108),
 (0.9999926732558264, 419318),
 (0.999992610509113, 637751),
 (0.9999922575615796, 687156),
 (0.999992051313499, 408668),
 (0.9999917387003919, 706802),
 (0.9999915699927856, 815011)]

In [ ]:
df_serial = list(zip(df_priv_raw_cs[0], df_priv_raw_cs['JOIN_SN']))
sim_scores = sorted(df_serial, key = lambda x: x[0], reverse = True)
sim_scores = sim_scores[1:21]
sim_scores
df_indices = [idx[1] for idx in sim_scores]
df_indices

[691574,
 997869,
 706288,
 891848,
 510055,
 1015400,
 460991,
 886777,
 964118,
 850732,
 876192,
 595474,
 727952,
 421108,
 419318,
 637751,
 687156,
 408668,
 706802,
 815011]

In [ ]:
# 대출 상품 코드를 하나의 리스트로
df_list1 = df_priv['LN_CD_1'].to_list()
df_list2 = df_priv['LN_CD_2'].to_list()
df_list3 = df_priv['LN_CD_3'].to_list()
LN_CD_list = []
i = 0
while i != 88392:
    temp_str = ''
    temp_str = temp_str + str((df_list1[i]))
    temp_str = temp_str + ', ' + str((df_list2[i]))
    temp_str = temp_str + ', ' + str((df_list3[i]))
    LN_CD_list.append(temp_str)
    i+=1
df_priv['LN_CD_list'] = LN_CD_list
df_priv_selected = df_priv.query('JOIN_SN in @df_test_index')
df_priv_selected

,JOIN_SN,CD_USG_AMT,CD_CA_AMT,AGE,CD_OPN_CD_2_1,GENDER,CD_CA_LMT,DLQ_CD_1_101,CD_USG_LMT,DLQ_RGST_AMT_max,...,DLQ_CD_1_105,PUB_DLQ_CD_1_604,is_applied,LN_CD_1,LN_CD_2,LN_CD_3,LN_DT,LN_AMT,RATE,LN_CD_list
0,787068,33040.0,0.0,38,5.0,2,5895.555556,0.0,23966.666667,0.0,...,0.0,0.0,1.0,31.0,100.0,0.0,201801.0,14000.0,4700.0,"31.0, 100.0, 0.0"
9,496097,30930.0,0.0,65,2.0,1,5892.000000,0.0,18000.000000,0.0,...,0.0,0.0,1.0,31.0,100.0,0.0,200003.0,40000.0,4080.0,"31.0, 100.0, 0.0"
10,496097,30930.0,0.0,65,2.0,1,5892.000000,0.0,18000.000000,0.0,...,0.0,0.0,1.0,31.0,100.0,0.0,201303.0,40000.0,4100.0,"31.0, 100.0, 0.0"
31,467779,12890.0,0.0,47,3.0,1,4266.666667,0.0,13933.333333,0.0,...,0.0,0.0,1.0,31.0,510.0,0.0,201509.0,1200.0,17900.0,"31.0, 510.0, 0.0"
68,683260,4470.0,0.0,68,2.0,2,1000.000000,0.0,2500.000000,0.0,...,0.0,0.0,1.0,31.0,200.0,0.0,201810.0,20000.0,0.0,"31.0, 200.0, 0.0"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88365,1868069,0.0,0.0,66,0.0,2,0.000000,0.0,0.000000,0.0,...,0.0,0.0,1.0,31.0,100.0,0.0,200209.0,2100.0,0.0,"31.0, 100.0, 0.0"
88366,1868069,0.0,0.0,66,0.0,2,0.000000,0.0,0.000000,0.0,...,0.0,0.0,1.0,31.0,100.0,0.0,200407.0,3700.0,0.0,"31.0, 100.0, 0.0"
88385,1731608,70780.0,0.0,46,3.0,2,4540.000000,0.0,13640.000000,0.0,...,0.0,0.0,1.0,31.0,220.0,0.0,201912.0,53000.0,3100.0,"31.0, 220.0, 0.0"
88386,1731608,70780.0,0.0,46,3.0,2,4540.000000,0.0,13640.000000,0.0,...,0.0,0.0,1.0,31.0,240.0,0.0,201807.0,40250.0,1300.0,"31.0, 240.0, 0.0"
88387,1731608,70780.0,0.0,46,3.0,2,4540.000000,0.0,13640.000000,0.0,...,0.0,0.0,1.0,31.0,270.0,0.0,201807.0,35000.0,1300.0,"31.0, 270.0, 0.0"

In [ ]:
j = 0
df_result = []
while j != 16539:
    df_serial = list(zip(df_priv_raw_cs[j], df_priv_raw_cs['JOIN_SN']))
    sim_scores = sorted(df_serial, key = lambda x: x[0], reverse = True)
    sim_scores = sim_scores[1:201]
    sim_scores
    df_indices = [idx[1] for idx in sim_scores]
    df_indices
    temp = df_priv.query('JOIN_SN in @df_indices')['LN_CD_list'].mode()[0]
    df_result.append(temp)
    j+=1

In [ ]:
df_priv_raw_cs['result'] = df_result

In [ ]:
temp = df_priv_raw_cs.query('JOIN_SN in @df_test_index')['result']
temp_list = temp.to_list()
df_selected['result'] = temp_list

<ipython-input-23-692d8a7fd6ae>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['result'] = temp_list

In [ ]:
k = 0
df_temp = df_priv_selected[['JOIN_SN', 'LN_CD_list']]
temp_list2 = []
while k != 4135:
    df_temp1 = df_temp[df_temp['JOIN_SN'] == df_test_index[k]]
    # temp_list = df_temp['LN_CD_list'].to_list()
    temp_list2.append(df_temp1['LN_CD_list'].to_list())
    k+=1
df_selected['LN_CD_list_merged'] = temp_list2
df_selected

<ipython-input-24-6f756de832d8>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['LN_CD_list_merged'] = temp_list2

,0,1,2,3,4,5,6,7,8,9,...,16532,16533,16534,16535,16536,16537,16538,JOIN_SN,result,LN_CD_list_merged
0,1.000000,0.656340,0.998630,0.999768,0.998030,0.999134,0.999720,0.999406,0.999895,0.999371,...,0.998867,0.999424,0.998630,0.997485,0.999837,0.999733,0.999601,787068,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
3,0.999768,0.656250,0.997338,1.000000,0.998939,0.998060,0.999151,0.998449,0.999374,0.998396,...,0.997639,0.998480,0.997338,0.998772,0.999937,0.999327,0.999184,496097,"31.0, 100.0, 0.0","[31.0, 150.0, 0.0, 31.0, 150.0, 0.0, 31.0, 150..."
8,0.999895,0.656178,0.999136,0.999374,0.997265,0.999520,0.999755,0.999753,1.000000,0.999728,...,0.999369,0.999803,0.999136,0.996395,0.999524,0.999651,0.999758,467779,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]"
14,0.998997,0.655722,0.999971,0.997866,0.994644,0.999994,0.999646,0.999914,0.999409,0.999927,...,0.999971,0.999771,0.999970,0.993635,0.998253,0.999402,0.998695,683260,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]"
15,0.906781,0.597523,0.886836,0.915361,0.925446,0.891058,0.901801,0.892734,0.900652,0.892401,...,0.887473,0.892068,0.886835,0.934069,0.913073,0.905283,0.900077,455254,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 100..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16516,0.998807,0.655565,0.999991,0.997574,0.994222,0.999972,0.999504,0.999878,0.999291,0.999895,...,0.999989,0.999747,0.999991,0.993099,0.997987,0.999218,0.998588,1857144,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
16528,0.992305,0.651049,0.984537,0.994514,0.996930,0.986368,0.989368,0.987670,0.990893,0.987504,...,0.985500,0.988215,0.984536,0.997426,0.993742,0.990044,0.992080,91957,"31.0, 100.0, 0.0","[31.0, 245.0, 0.0, 31.0, 245.0, 900.0, 31.0, 2..."
16531,0.998630,0.655477,1.000000,0.997338,0.993864,0.999942,0.999425,0.999807,0.999136,0.999828,...,0.999965,0.999644,0.999999,0.992755,0.997777,0.999131,0.998359,167148,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
16534,0.998630,0.655477,0.999999,0.997338,0.993864,0.999941,0.999425,0.999806,0.999136,0.999827,...,0.999964,0.999644,1.000000,0.992755,0.997777,0.999131,0.998359,1868069,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 220..."
16537,0.999733,0.656384,0.999131,0.999327,0.997084,0.999472,0.999964,0.999522,0.999651,0.999509,...,0.999177,0.999336,0.999131,0.996801,0.999513,1.000000,0.998930,1731608,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0]"

In [ ]:
# 대출 상품 1개 추천 평가
result_list = df_selected['result'].to_list()
LN_CD_list_merged = df_selected['LN_CD_list_merged'].to_list()

p = 0
value_list = []
for i in result_list:
    if i in LN_CD_list_merged[p]:
        value_list.append(1)
    else:
        value_list.append(0)
    p+=1

In [ ]:
# 여러 개 동시에
j = 0
df_result = []
df_temp = df_priv_selected[['JOIN_SN', 'LN_CD_list']]
temp_list3 = []
while j != 4135:
    df_serial = list(zip(df_priv_raw_cs[j], df_priv_raw_cs['JOIN_SN']))
    sim_scores = sorted(df_serial, key = lambda x: x[0], reverse = True)
    sim_scores = sim_scores[1:71]
    sim_scores
    df_indices = [idx[1] for idx in sim_scores]
    df_indices
    df_temp1 = df_temp[df_temp['JOIN_SN'] == df_test_index[j]]
    list_len = len(df_temp1['LN_CD_list'].to_list())
    temp_df = pd.DataFrame(df_priv.query('JOIN_SN in @df_indices')['LN_CD_list'].value_counts())
    temp_list = temp_df.reset_index()['index'].to_list()[:list_len]
    df_result.append(temp_list)
    j+=1

In [ ]:
df_selected['len_result'] = df_result
df_selected

In [ ]:
#여러 개 길이 맞춰서 추천
len_result = df_selected['len_result'].to_list()
result_list = df_selected['result'].to_list()
LN_CD_list_merged = df_selected['LN_CD_list_merged'].to_list()

q = 0
value_list = []
while q != 4135:
    value = 0
    for i in len_result[q]:
        if i in LN_CD_list_merged[q]:
            value += 1
        else:
            value += 0
    value_list.append(value)
    q+=1 
value_list

In [ ]:
len(value_list)

4135

In [ ]:
value_list.count(1)

1500

In [27]:
print("top 20 Precision@1 :", 1287.0/4135) 
print("top 30 Precision@1 :", 1357.0/4135)
print("top 40 Precision@1 :", 1383.0/4135)
print("top 50 Precision@1 :", 1416.0/4135)
print("top 60 Precision@1 :", 1428.0/4135)
print("top 70 Precision@1 :", 1451.0/4135)
print("top 80 Precision@1 :", 1457.0/4135)
print("top 90 Precision@1 :", 1465.0/4135)
print("top 100 Precision@1 :", 1485.0/4135)

top 20 Precision@1 : 0.31124546553808946
top 30 Precision@1 : 0.32817412333736395
top 40 Precision@1 : 0.3344619105199516
top 50 Precision@1 : 0.34244256348246677
top 60 Precision@1 : 0.34534461910519954
top 70 Precision@1 : 0.350906892382104
top 80 Precision@1 : 0.3523579201934704
top 90 Precision@1 : 0.3542926239419589
top 100 Precision@1 : 0.3591293833131802

#### 금리, 대출 금액 정리 데이터

In [ ]:
index_list = df_selected.reset_index()['index'].to_list()

In [ ]:
df_selected

,0,1,2,3,4,5,6,7,8,9,...,16532,16533,16534,16535,16536,16537,16538,JOIN_SN,result,LN_CD_list_merged
0,1.000000,0.656340,0.998630,0.999768,0.998030,0.999134,0.999720,0.999406,0.999895,0.999371,...,0.998867,0.999424,0.998630,0.997485,0.999837,0.999733,0.999601,787068,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
3,0.999768,0.656250,0.997338,1.000000,0.998939,0.998060,0.999151,0.998449,0.999374,0.998396,...,0.997639,0.998480,0.997338,0.998772,0.999937,0.999327,0.999184,496097,"31.0, 100.0, 0.0","[31.0, 150.0, 0.0, 31.0, 150.0, 0.0, 31.0, 150..."
8,0.999895,0.656178,0.999136,0.999374,0.997265,0.999520,0.999755,0.999753,1.000000,0.999728,...,0.999369,0.999803,0.999136,0.996395,0.999524,0.999651,0.999758,467779,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]"
14,0.998997,0.655722,0.999971,0.997866,0.994644,0.999994,0.999646,0.999914,0.999409,0.999927,...,0.999971,0.999771,0.999970,0.993635,0.998253,0.999402,0.998695,683260,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]"
15,0.906781,0.597523,0.886836,0.915361,0.925446,0.891058,0.901801,0.892734,0.900652,0.892401,...,0.887473,0.892068,0.886835,0.934069,0.913073,0.905283,0.900077,455254,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 100..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16516,0.998807,0.655565,0.999991,0.997574,0.994222,0.999972,0.999504,0.999878,0.999291,0.999895,...,0.999989,0.999747,0.999991,0.993099,0.997987,0.999218,0.998588,1857144,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
16528,0.992305,0.651049,0.984537,0.994514,0.996930,0.986368,0.989368,0.987670,0.990893,0.987504,...,0.985500,0.988215,0.984536,0.997426,0.993742,0.990044,0.992080,91957,"31.0, 100.0, 0.0","[31.0, 245.0, 0.0, 31.0, 245.0, 900.0, 31.0, 2..."
16531,0.998630,0.655477,1.000000,0.997338,0.993864,0.999942,0.999425,0.999807,0.999136,0.999828,...,0.999965,0.999644,0.999999,0.992755,0.997777,0.999131,0.998359,167148,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]"
16534,0.998630,0.655477,0.999999,0.997338,0.993864,0.999941,0.999425,0.999806,0.999136,0.999827,...,0.999964,0.999644,1.000000,0.992755,0.997777,0.999131,0.998359,1868069,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 220..."
16537,0.999733,0.656384,0.999131,0.999327,0.997084,0.999472,0.999964,0.999522,0.999651,0.999509,...,0.999177,0.999336,0.999131,0.996801,0.999513,1.000000,0.998930,1731608,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0]"

In [ ]:
j = 0
df_result = []
temp_list_max = []
temp_list_min = []
temp_listR_max = []
temp_listR_min = []

while j != 4135:
    df_serial = list(zip(df_priv_raw_cs[j], df_priv_raw_cs['JOIN_SN']))
    sim_scores = sorted(df_serial, key = lambda x: x[0], reverse = True)
    sim_scores = sim_scores[1:51]
    sim_scores
    df_indices = [idx[1] for idx in sim_scores]
    df_indices
    q = index_list[j]
    temp1 = df_selected['result'][q].replace(' ', '').split(',')[0]
    temp2 = df_selected['result'][q].replace(' ', '').split(',')[1]
    temp3 = df_selected['result'][q].replace(' ', '').split(',')[2]
    temp1 = float(temp1)
    temp2 = float(temp2)
    temp3 = float(temp3)
    temp = df_priv.query('JOIN_SN in @df_indices')
    temp = temp.query('LN_CD_1 == @temp1')
    temp = temp.query('LN_CD_2 == @temp2')
    temp = temp.query('LN_CD_3 == @temp3')
    temp_max = temp['LN_AMT'].max()
    temp_min = temp['LN_AMT'].min()
    tempR_max = temp['RATE'].max()
    tempR_min = temp['RATE'].min()
    temp_list_max.append(temp_max)
    temp_list_min.append(temp_min)
    temp_listR_max.append(tempR_max)
    temp_listR_min.append(tempR_min)
    j+=1

df_selected['LN_AMT_max'] = temp_list_max
df_selected['LN_AMT_min'] = temp_list_min
df_selected['RATE_max'] = temp_listR_max
df_selected['RATE_min'] = temp_listR_min
df_selected

<ipython-input-29-0bb84574ed93>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['LN_AMT_max'] = temp_list_max
<ipython-input-29-0bb84574ed93>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['LN_AMT_min'] = temp_list_min
<ipython-input-29-0bb84574ed93>:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['RATE_max'] = temp_listR_max
<ipython-input-29-0bb84574ed93>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['RATE_min'] = temp_listR_min

,0,1,2,3,4,5,6,7,8,9,...,16536,16537,16538,JOIN_SN,result,LN_CD_list_merged,LN_AMT_max,LN_AMT_min,RATE_max,RATE_min
0,1.000000,0.656340,0.998630,0.999768,0.998030,0.999134,0.999720,0.999406,0.999895,0.999371,...,0.999837,0.999733,0.999601,787068,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]",120000.0,1950.000000,5950.0,2300.0
3,0.999768,0.656250,0.997338,1.000000,0.998939,0.998060,0.999151,0.998449,0.999374,0.998396,...,0.999937,0.999327,0.999184,496097,"31.0, 100.0, 0.0","[31.0, 150.0, 0.0, 31.0, 150.0, 0.0, 31.0, 150...",140000.0,1585.714286,24000.0,0.0
8,0.999895,0.656178,0.999136,0.999374,0.997265,0.999520,0.999755,0.999753,1.000000,0.999728,...,0.999524,0.999651,0.999758,467779,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]",12000.0,100.000000,19900.0,0.0
14,0.998997,0.655722,0.999971,0.997866,0.994644,0.999994,0.999646,0.999914,0.999409,0.999927,...,0.998253,0.999402,0.998695,683260,"31.0, 100.0, 0.0","[31.0, 500.0, 0.0]",100000.0,2600.000000,7350.0,2500.0
15,0.906781,0.597523,0.886836,0.915361,0.925446,0.891058,0.901801,0.892734,0.900652,0.892401,...,0.913073,0.905283,0.900077,455254,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 100...",160000.0,900.000000,24000.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16516,0.998807,0.655565,0.999991,0.997574,0.994222,0.999972,0.999504,0.999878,0.999291,0.999895,...,0.997987,0.999218,0.998588,1857144,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]",140000.0,570.000000,12900.0,1200.0
16528,0.992305,0.651049,0.984537,0.994514,0.996930,0.986368,0.989368,0.987670,0.990893,0.987504,...,0.993742,0.990044,0.992080,91957,"31.0, 100.0, 0.0","[31.0, 245.0, 0.0, 31.0, 245.0, 900.0, 31.0, 2...",12000.0,100.000000,24000.0,0.0
16531,0.998630,0.655477,1.000000,0.997338,0.993864,0.999942,0.999425,0.999807,0.999136,0.999828,...,0.997777,0.999131,0.998359,167148,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0]",65000.0,2666.666667,23900.0,0.0
16534,0.998630,0.655477,0.999999,0.997338,0.993864,0.999941,0.999425,0.999806,0.999136,0.999827,...,0.997777,0.999131,0.998359,1868069,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0, 31.0, 220...",42000.0,730.000000,24000.0,0.0
16537,0.999733,0.656384,0.999131,0.999327,0.997084,0.999472,0.999964,0.999522,0.999651,0.999509,...,0.999513,1.000000,0.998930,1731608,"31.0, 100.0, 0.0","[31.0, 100.0, 0.0, 31.0, 100.0, 0.0]",39000.0,550.000000,17400.0,0.0

In [ ]:
df_selected.to_csv('/content/drive/Shareddrives/데캡디/Result/RATE_AMT_data/RATE_AMT_data_priv.csv', index = False)

In [ ]:
temp_df = pd.read_csv('/content/drive/Shareddrives/데캡디/Result/RATE_AMT_data/RATE_AMT_data_priv.csv')

FileNotFoundError: ignored